type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$"]

encoding: plain
#include_lines: ['^data:image/png;base64,']
harvester_buffer_size: 10485760
max_bytes: 10485760

close_eof: true
clean_removed: true

processors:
- add_locale: ~
- script:
    lang: javascript
    id: gem_configImg
    params:
      m5outTime: "${M5OUT_MODIFICATION_TIME_FIELD}"
    source: >
      var m5outTime;
      function register(scriptParams) {
          m5outTime = scriptParams.m5outTime;
      }
      function process(event) {
          event.Delete("event.module");
          event.Delete("input.type");
          event.Delete("log.file");
          event.Delete("log.offset");
          event.Delete("log.flags");
          event.Delete("fileset.name");
          event.Delete("service.type");
          //ecs.version is added after beats event
          //event.Delete("ecs.version");
          //event.Delete("host.name");

          event.Put("gem5.timestamp", m5outTime);

          var message = event.Get("message");
          event.Put("gem5.configImg", message);
          event.Delete("message");
      }
#- decode_base64_field:
#    field:
#      from: "message"
#      to: "gem5.configImg"
#- drop_fields:
#    fields: ["message"]
#    ignore_missing: true
