type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}

harvester_buffer_size: 200000 

close_eof: true
clean_removed: true
exclude_files: [".gz$"]

multiline:
  pattern: '^{'
  negate: true
  match: after
  max_lines: 1000
  timeout: 10s

processors:
- script:
    lang: javascript
    id: gem_config
    source: >
      function process(event) {
          event.Delete("event.module");
          event.Delete("input.type");
          event.Delete("log.file");
          event.Delete("log.offset");
          event.Delete("log.flags");
          event.Delete("fileset.name");
          event.Delete("service.type");
          //ecs.version is added after beats event
          //event.Delete("ecs.version");
          //event.Delete("host.name");

          var gemConfigMessage = event.Get("message");
          event.Delete("message");
          gemConfigMessage = gemConfigMessage + "}";
          gemConfigMessage = gemConfigMessage.replace(/\s*/g,"");
          event.Put("gem5.config", gemConfigMessage);
      }
- decode_json_fields:
    fields: ["gem5.config"]
    process_array: true
    max_depth: 9
    overwrite_keys: true
# I do not know whether the following processor works, may be not, but I just keep them
- decode_json_fields:
    fields: ["gem5.config.system.cpu","gem5.config.system.mem_ctrls","gem5.config.system.redirect_paths"]
    process_array: true
    max_depth: 9
    overwrite_keys: true
