type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}

harvester_buffer_size: 200000 

close_eof: true
#clean_inactive: 3s
clean_removed: true

exclude_files: [".gz$"]

#json:
#  keys_under_root: true 
#  overwrite_keys: true
#  add_error_key: true
#  document_id: true

multiline:
  pattern: '^{'
  negate: true
  match: after
  flush_pattern: '^}'

processors:
- script:
    lang: javascript
    id: gem_config
    source: >
      function process(event) {
          event.Delete("event.module");
          event.Delete("input.type");
          event.Delete("log.file");
          event.Delete("log.offset");
          event.Delete("log.flags");
          event.Delete("fileset.name");
          event.Delete("service.type");
          //ecs.version is added after beats event
          //event.Delete("ecs.version");
          //event.Delete("host.name");

          var gemConfigMessage = event.Get("message");
          gemConfigMessage = gemConfigMessage.replace(/\s*/g,"");
          event.Delete("message");
          event.Put("message", gemConfigMessage);
      }
