type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$"]

close_eof: true
clean_removed: true

processors:
- add_locale: ~
- script:
    lang: javascript
    id: gem_ExecBar
    params:
      m5outTime: "${M5OUT_MODIFICATION_TIME_FIELD}"
    source: >
      var m5outTime;
      function register(scriptParams) {
          m5outTime = scriptParams.m5outTime;
      }
      function process(event) {
          event.Delete("event.module");
          event.Delete("input.type");
          event.Delete("log.file");
          event.Delete("log.offset");
          event.Delete("log.flags");
          event.Delete("fileset.name");
          event.Delete("service.type");
          event.Put("gem5.timestamp", m5outTime);

          var message = event.Get("message");
          var line = message.split(' ');
          event.Put("gem5.Exec.Bar.X-axis", Number(line[0]));
          event.Put("gem5.Exec.Bar.Y-axis", Number(line[1]));
          event.Delete("message");
      }
