type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}

harvester_buffer_size: 70000

close_eof: true
#clean_inactive: 3s
clean_removed: true

exclude_files: [".gz$"]

multiline.pattern: '^-+[\s]*Begin Simulation Statistics[\s]*-+'
multiline.negate: true
multiline.match: after
multiline.flush_pattern: '^-+[\s]*End Simulation Statistics[\s]*-+'

#fields
#tags
#index

processors:
- script:
    lang: javascript
    id: gem_stats
    params:
      m5outTime: "${M5OUT_MODIFICATION_TIME_FIELD}"
    source: >
      var m5outTime;
      function register(scriptParams) {
          m5outTime = scriptParams.m5outTime;
      }
      function process(event) {
          event.Delete("event.module");
          event.Delete("input.type");
          event.Delete("log.file");
          event.Delete("log.offset");
          event.Delete("log.flags");
          event.Delete("fileset.name");
          event.Delete("service.type");
          //ecs.version is added after beats event
          //event.Delete("ecs.version");
          //event.Delete("host.name");

          //m5outTime = new Date(m5outTime).toISOString();
          event.Put("event.timestamp", m5outTime);

          var gemStatsMessage = event.Get("message");
          var lines = gemStatsMessage.split(/\n/);
          for(var lineNum=0; lineNum<lines.length; ++lineNum) {
              var line = lines[lineNum];
              if(line.length != 0) {
                  if(line[0]<"z" && line[0]>"a") {
                      var pos = line.indexOf("#");
                      line = line.slice(0, pos);
                      line = line.split(/\s+/);
                      var name = line[0];
                      name = "gem5.stats." + name;
                      for(var j=1; j<line.length-1; ++j) {
                          if (isNaN(line[j])) {
                              event.AppendTo(name, line[j]);
                          } else {
                              event.AppendTo(name, Number(line[j]));
                          }
                      }
                  }
              }
          }
          event.Delete("message");
      }
- timestamp:
    field: event.timestamp
    layouts:
      - 'Mon Jan _2 15:04:05 MST 2006'
    test:
      - 'Tue Mar 31 19:19:59 CST 2020'
- drop_fields:
    fields: event.timestamp

