type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$"]

harvester_buffer_size: 200000

close_eof: true
#clean_inactive: 3s
clean_removed: true

tail_files = true

multiline.pattern: '^[0-9]+: CPU:'
multiline.negate: true
multiline.match: after
multiline.flush_pattern: '^[0-9]+: CPU:'

processors:
- add_locale: ~
- script:
    lang: javascript
    id: gem_SimpleSSDLog
    params:
      m5outTime: "${M5OUT_MODIFICATION_TIME_FIELD}"
    source: >
      var m5outTime;
      function register(scriptParams) {
          m5outTime = scriptParams.m5outTime;
      }
      function process(event) {
      }
