type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$"]

close_eof: true
clean_removed: true

processors:
- script:
    lang: javascript
    id: gem_dram
    params:
      m5outTime: "${M5OUT_MODIFICATION_TIME_FIELD}"
    source: >
      var m5outTime;
      function register(scriptParams) {
          m5outTime = scriptParams.m5outTime;
      }
      function process(event) {
          event.Delete("event.module");
          event.Delete("input.type");
          event.Delete("log.flags");
          event.Delete("fileset.name");
          event.Delete("service.type");

          var gemDramMessage = event.Get("message");
          var hexIndex = gemDramMessage.search(/0[xX][0-9a-fA-F]+\s*$/);
          if (hexIndex != -1) {
              var strHex = gemDramMessage.slice(hexIndex);
              var numInt = parseInt(strHex, 16);
          }

          event.Put("gem5.dram.address", numInt);

          //m5outTime = new Date(m5outTime).toISOString();
          event.Put("gem5.timestamp", m5outTime);
      }
#- timestamp:
#    field: event.CreateTime
#    layouts:
#      - 'Mon Jan _2 15:04:05 MST 2006'
#    test:
#      - 'Tue Mar 31 19:19:59 CST 2020'
